### ISSUE TITLE
3.0.0.6  Launch button launches steam version instead of modded version.

### ISSUE THREAD

**Issue by ThaSiouL** [MatuxGG/ModManager#12]
When I launch a game from the 3.0.0.6 button the steam version gets executed. While i know this is intentional, me and my friend group have copied the folder for modding so we don't have to install/uninstall it and to not get blindsided by game updates. is there any possibility to revert it to the previous functionality or at least give us an option in the settings to launch the exe in the selected folder.

**Comment by MatuxGG** [comment]
Hello,

Modding another folder than the folder stored in Steam is not recommended. Often Steam is reloaded by itself and mods are not correctly loaded. I highly recommend to make a backup of your Among Us directory and then, fully use Mod Manager to switch between modded and unmodded Among Us.

As well, this fixes two issues once :
- For some people, windows explorer was launched instead of Among Us because the path contained special characters like "é" for example.
- It was complicated to launch Among Us as simple user because Mod Manager is running admin privileges.  Therefore, they were issues with other programs like Discord mainly.

For all these reasons, a revert is not a thing in the future, sorry.
Now, you can even launch the game multiple times from Mod Manager.

Best regards,
