### ISSUE TITLE
Problem :c

### ISSUE THREAD

**Issue by daniel95000** [MatuxGG/ModManager#15]
Hello I have a problem and it is that when I try to start the Modloader I get this error and the modloader does not open :c 

"Can´t reach Mod Manager server. Please verify your internet connection and try again!"

**Comment by MatuxGG** [comment]
It happens when you're not able to reach the server.
It can be because you're using an unstable connection or your firewall/antivirus is blocking matux.fr (or 152.228.160.91)

**Comment by daniel95000** [comment]
is there any way to fix them? :(

**Comment by MatuxGG** [comment]
It depens on your antivirus. If you have any external software on your computer, you're supposed to know how it works and I can't do much for you unfortunately.

**Comment by Lyelt** [comment]
This error is not exclusive to when the server cannot be reached. There is a lot of code that can fail that would cause this error message to appear. In my case, for example, I found that this line in `ModList.cs` `installDependencies()` was throwing:

```
ZipFile.ExtractToDirectory(tempPath + "\\" + dependencie + ".zip", this.modManager.config.amongUsPath);
```

because the file(s) it was attempting to extract already existed. Yet, I still received the "Can't reach Mod Manager server" message because the `catch` displays the same error regardless of what actually went wrong.

**Comment by MatuxGG** [comment]
You're right. Gonna fix this soon.

Thanks for the report

**Comment by MatuxGG** [comment]
It should be fixed now, thanks for the report ! :)
