### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by zachariapopcorn** [MatuxGG/ModManager#2]
When installing mods (the only ones that I used were the Quantum and Confusion mods), if you start a game, it's just a black screen and you can't do anything, is this just a bug or is it installing corrupt mods?

**Comment by MatuxGG** [comment]
Hello, for me, using these two mods works pretty well.
Are you facing this bug each time you launch Among Us ? Because, even without mods, this already happened to me many times. I don't know, sometimes the game is bugged but relaunching it, most of the time, fixes this issue.

If you're still not able to launch the game, can you give me a few more informations please ?
This can help me :
- A screenshot of Mod Manager when launched
- A screenshot of your Among Us folder (Click "Open" in Mod Manager)
- In the previous directory, a screenshot of BepInEx > plugins

Anyway, thanks for reporting this issue :)

**Comment by zachariapopcorn** [comment]
@MatuxGG

ModManager when launched: https://i.imgur.com/zVdgfka.png
Among Us Folder: https://i.imgur.com/udnX7j7.png
Plugins Folder: https://i.imgur.com/8vQDkYU.png

**Comment by MatuxGG** [comment]
Everything looks ok. Maybe, there is an issue with the mods themselves but it's not linked to Mod Manager. Everything that Mod Manager should have done here is done, apparently.

In theory, I should be possible to use any of CheapYT mods together mods tho. This particular combination works for me : 

![image](https://user-images.githubusercontent.com/12508157/108104606-cf8fb980-708b-11eb-8750-0d10b0956e61.png)

Maybe you should contact Cheap YT directly.

**Comment by zachariapopcorn** [comment]
I'm able to launch the game, but I can't actually play games as when they load, it's just a black screen for me

**Comment by FearlessFlo** [comment]
Mainly what you describe happens if not every Player in the lobby installed and loaded the same mod you did.
So you need to ensure that every Player loaded the same Version of mod you loaded.

**Comment by zachariapopcorn** [comment]
Oh, that's kinda shit ngl, but yea, I was on 2.0.1 while they were on 2.0.0

**Comment by NarfShaDoWs24** [comment]
The thing I had to do to fix it for me on the cheap yt mods was to download their file here https://cheep-yt.com/file.php?id=4569 
and replace it in the mod manager files. 

Mod Manager\files\dependencies\BepInEx and then replace the core file. It started working for me after that.

**Comment by MatuxGG** [comment]
I'll give it a look for next patches

**Comment by jono99** [comment]
HI @MatuxGG 

I had a similar black screen problem, only I had 6 instances of the same folder copied running to test and they all failed. So I can't see it being missing mods or incorrect versions. You are still able to click things and have an effect on the game though which is strange.

I used a stock setup of among us and just installed "Town of Impostors" with CrowdedMod (10+ players setting). That server didn't allow more than 10 players either. Then I tried my local custom server and the black screen occurred. Not sure If I need to setup anything on server specifically

**Comment by MatuxGG** [comment]
Honestly, I'm not a specialist of servers. I'm currently only running one that allows 10+players+ with no plugin installed.
Did you try on it ?
I didn't play that much Town of impostors too.

Either way, I'm often available the evening on Mod Manager discord if you want some help in a voice channel.

**Comment by MatuxGG** [comment]
Mod Manager doesn't provide AllOfUs for now and there is a reason. The AllOfUs team doesn't want you to use other mods with theirs (Mod Manager used to include their mods and that's why they're not here anymore). That's almost the same for CheepYT mods.

When you click on Activate 10+ players lobbies on Matux server, it should work. And behind this functionnality, there is Crowded mod configured. From my tests, it seemed to work well with all mods in Mod Manager. I even tried with Town Of Impostors today.

As well, using multiple mods at the same time is possible but it's at your own risks, once again. Prefer using bundle mods like Town Of Us to play with different mods. CustomKeyBinds is almost compatible with everything too.
