### ISSUE TITLE
Can't connect to Steam account

### ISSUE THREAD

**Issue by Entity202s** [MatuxGG/ModManager#41]
so i own the steam version of among us, and in order to play you have to launch through steam, otherwise it locks you out of your account until you launch from steam, and it you launch from steam even if you put the mods in the files where they should work, they dont, some things work some things dont, aulauncher i believe works but i have no clue how it works, this i do know how it works but it wont work with steam accounts.

**Comment by MatuxGG** [comment]
Hi,

First, thanks for your comment.

In order to make it work correctly, you have to select "Steam" as launcher in settings.
You also need to have steam opened when you start a mod. Then, please click on the start button on the same line of the mod, not on "Start vanilla Among us".

If it still doesn't work, please reply this or open a ticket in the discord server ;)

**Comment by MatuxGG** [comment]
I close the issue as you didn't answer recently.
Feel free to open another one if it's still not solved.
The recommended way to be helped is the discord server tho.
