### ISSUE TITLE
Loading Local Files 

### ISSUE THREAD

**Issue by Nekkin** [MatuxGG/ModManager#46]
Whenever I start to run mod manager it loads but when it's loading it says loading local files and won't let me click on anything or show any mods. The first time I loaded up Mod Manager (MM), it worked, but whenever I load it up, it just freezes on Loading Local Files. I tried downloading and redownloading MM but it still says Loading Local Config. Is there a fix to Loading Local Config or does it just not work for me? 

P.S. I think the problem might be with the net framework, but I also don't know how to do that It auto-installed the first time but if I reinstall MM it doesn't auto-install the framework. Thank you and let me know if you found an answer.  

Edit: My discord is Poopyman69#0448 If u need 

![Among us](https://user-images.githubusercontent.com/121470339/209603795-fd585c0d-efbe-4451-b7b7-eda30a24f7f4.png)

**Comment by MatuxGG** [comment]
Hi,

This issue is decribed on discord. Please, prefer using discord next time for support requests ;)

This issue is related to a bug in a previous version of ModManager.

If you had any local mod you want to keep, please backup your local mod by saving the files located in %appdata%/ModManager/localMods.
Otherwise, just do the following :
- Press windows + R
- Enter %appdata%
- Remove ModManager

Sorry for the inconvenience.

**Comment by Nekkin** [comment]
Thank you it worked
