### ISSUE TITLE
Unselect Mod and error

### ISSUE THREAD

**Issue by WilliamVercken** [MatuxGG/ModManager#6]
Hi,

Once a mod is selected, we can't unselect it. Whatever I do, it's still green, unless I update mods.

Version 2.0.0.5

OH !! Quick update just before posting, and I found a big bug !
When I have one or several mods selected, I click on Town of Us, and other mods get unselected. But when I click to another mod, then I have an error.

![image](https://user-images.githubusercontent.com/1272792/109195396-c0e78780-779a-11eb-8c9d-4fd9d5885d74.png)

https://pastebin.com/raw/c8CdQ5xs

Restarting the Mod Manager doesn't fix it, I have to update mods to be able to click on another mods again.

**Comment by MatuxGG** [comment]
I'm aware of all this.

Right now, the install process is limited for a certain amount of mods. And Town Of Us is one of them.
Right now, I'm working on a bigger update that is almost finished and that solves this issue.

But, Town Of Us is really insane so I still decided to add it with a special installation process. One of the thing that you can't do is using it with other mods right now. That's why you have this issue.

Except Town of us, you can combine mods at your own risks but you can't disable individually a mod. You can only enable a new one (then, it's green) or, at any point, disable all mods with the red button in the bottom left corner ("remove mods") to get a clean Among Us. 

I'm adding mods daily still so don't hesitate to press "Update mods".

If you have any more questions, issue or time to spend, there is a discord server for Mod Manager : https://discord.gg/yBNgKuGjNw. For example, recently I asked people for translations in their respective languages but I don't think it will be that useful to ask you tho because je suis Français aussi ^^

Hopefully, I was eble to help you and you will enjoy  next update.

**Comment by WilliamVercken** [comment]
Oh, the button "remove mods" desactive the selected mods, ok !
I thought it delete the mods from the list ! Maybe you should change the wording, or is this only me? 😄 
Thank you for the discord link and for your answer!

**Comment by MatuxGG** [comment]
You're welcome !

You're right in a way. Next update will try to clarify many points and this will be one of them. I hope it will be better.

Thanks for your feedback :)
