### ISSUE TITLE
mod manager 3.0

### ISSUE THREAD

**Issue by landshark-07** [MatuxGG/ModManager#7]
Mod list repeats like 3 or 4 times and cheepyt mods are missing.  I did prefer the 2.0 interface too but i like the descriptions of all the mods since some mods i never heard of, hopefully you'll be able to make a blend of the them. thank you this is awesome job

**Comment by MatuxGG** [comment]
Hey,

You're right. Each time you go to settings, the mods are duplicated but it still works. I'll patch this asap ^^

Many things have been added in this version like the possibility of updating mods directly after its creator pusblishes a new release.

CheepYT doesn't want the install of other mods so for now, Mod Manager doesn't respect his terms of use. So for now, it's removed but I'm working on a solution to add them differently.

Thanks for your feedback :)

**Comment by landshark-07** [comment]
Hey
Nice job with it so far. i just updated and seen the update mods and noticed three new mods. I dont know if those mods are loading in or not though. i didnt see Pandapip1 name on the screen and no additional settings.

**Comment by MatuxGG** [comment]
Hey,

Thanks for the report ! The problem is on mods releases files. It should be solved soon.

The mod duplication that you previously reported has been fixed tho !

**Comment by landshark-07** [comment]
Yes it's not duplicating anymore. I'm also in you discord now so if I see anything I'll post it in there

**Comment by ArielV12345** [comment]
Yo thanks for this mod man it really helped also you should shoutout each of them because you "borrowed" their mods hopefully with the permission to do so.o

**Comment by MatuxGG** [comment]
First of all, thanks you :)

Actually, what Mod Manager does is :
- It downloads the mod from its official github repository (latest version and allows update if you have an older one)
- It does the installation in you Among Us directory
- That's all

In facts, I'm not storing or editing their mods. And mods are already public with the same instructions that can be done manually. I also check the license of every mod I add to Mod Manager (if there is one) and for now, there is no issue with that.

I didn't tell the authors (even if many are aware of it) because this is legal. If at some point, one of them asks me to remove their mod, I'll do it. I already did it with All Of Us Launchpad and CheepYT in the past.
